config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  resources :genus_notes
  resources :genus
  resources :sub_families
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/sub_family.rb
class SubFamily < ApplicationRecord
end

app/controllers/sub_families_controller.rb
class SubFamiliesController < ApplicationController
  before_action :set_sub_family, only: [:show, :edit, :update, :destroy]

  # GET /sub_families
  # GET /sub_families.json
  def index
    @sub_families = SubFamily.all
  end

  # GET /sub_families/1
  # GET /sub_families/1.json
  def show
  end

  # GET /sub_families/new
  def new
    @sub_family = SubFamily.new
  end

  # GET /sub_families/1/edit
  def edit
  end

  # POST /sub_families
  # POST /sub_families.json
  def create
    @sub_family = SubFamily.new(sub_family_params)

    respond_to do |format|
      if @sub_family.save
        format.html { redirect_to @sub_family, notice: 'Sub familia foi criada.' }
        format.json { render :show, status: :created, location: @sub_family }
      else
        format.html { render :new }
        format.json { render json: @sub_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_families/1
  # PATCH/PUT /sub_families/1.json
  def update
    respond_to do |format|
      if @sub_family.update(sub_family_params)
        format.html { redirect_to @sub_family, notice: 'Sub família foi atualizada.' }
        format.json { render :show, status: :ok, location: @sub_family }
      else
        format.html { render :edit }
        format.json { render json: @sub_family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_families/1
  # DELETE /sub_families/1.json
  def destroy
    genus = Genu.all;
    genus.each do |genu|
        if(genu.sub_family_id == @sub_family.id)
            genu.destroy
            end
    end
    @sub_family.destroy
    respond_to do |format|
      format.html { redirect_to sub_families_url, notice: 'Sub família foi deletada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_family
      @sub_family = SubFamily.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_family_params
      params.require(:sub_family).permit(:name, :created_at, :updated_at)
    end
end

app/helpers/sub_families_helper.rb
module SubFamiliesHelper
end

app/views/sub_families/_form.html.erb
<%= form_with(model: sub_family, local: true) do |form| %>
  <% if sub_family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_family.errors.count, "error") %> prohibited this sub_family from being saved:</h2>

      <ul>
        <% sub_family.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nome %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script>
$('input[name="commit"]').addClass('btn').addClass('btn-success');
</script>

app/views/sub_families/edit.html.erb
<h1>Editando sub familia</h1>

<%= render 'form', sub_family: @sub_family %>

</br>
<%= link_to raw('<button class="btn btn-primary">Mostrar</button>'), @sub_family %> |
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), sub_families_path %>


<script>
$('input[name="commit"]').val("Atualizar Sub Família");
</script>

app/views/sub_families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Famílias</h1>
<%= link_to raw('<button id="new1" class="btn btn-dark" style="float: right;margin-top: -45px;">Nova sub Famililia</button>'), new_sub_family_path %>
<table class="table table-stripped display" id="table1_id">
  <thead class="table-dark">
    <tr>
      <th>Nome</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @sub_families.each do |sub_family| %>
      <tr>
        <td><%= sub_family.name %></td>
        <td><%= link_to raw('<span style="color:black!important;" class="e1 fa fa-eye"></span> '), sub_family %> |
        <%= link_to raw('<span style="color:black!important;" class="e1 fa fa-pen"></span>'), edit_sub_family_path(sub_family) %> |
        <%= link_to raw('<span style="color:black!important;" class="fa fa-trash"></span>'), sub_family, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<br>
<script>
    $(document).ready(function () {
        $('#table1_id').DataTable({
                    "language": {
                        "info": "Mostrando Página _PAGE_ de _PAGES_",
                        "search": "",
                        "paginate": {
                            "next": "Próxima Página",
                            "previous": "Página Anterior"
                        }
                    },

                });
                $('.dataTables_length').hide();
                $('.dataTables_filter input').addClass('form-control').attr('placeholder','Procurar Sub Familília');
                $('.dataTables_filter').css('float','left');
    });

    $('#new1').on('click',function(){
        $('#table1_id_filter').remove();
        $('#table1_id_info').remove();
        $('#table1_id_paginate').remove();
    });

    $('.e1').on('click',function(){
            $('#table1_id_filter').remove();
            $('#table1_id_info').remove();
            $('#table1_id_paginate').remove();
        });

        $('.bt').on('click',function(){
                    $('#table1_id_filter').remove();
                    $('#table1_id_info').remove();
                    $('#table1_id_paginate').remove();
                });

</script>

app/views/sub_families/new.html.erb
<h1>Nova Sub Família</h1>

<%= render 'form', sub_family: @sub_family %>

</br>
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), sub_families_path %>

<script>
$('input[name="commit"]').val("Criar Sub Família");
</script>

app/views/sub_families/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
<tbody>
<tr>
  <th><strong>Nome:</strong><th>
  <td><%= @sub_family.name %></td>
</tr>

<tr>
  <th><strong>Criado em:</strong><th>
  <td><%= @sub_family.created_at %></td>
</tr>

<tr>
  <th><strong>Atualizado em:</strong><th>
  <td><%= @sub_family.updated_at %></td>
</tr>
</tbody>
</table>
<%= link_to raw('<button class="btn btn-primary">Editar</button>'), edit_sub_family_path(@sub_family) %> |
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), sub_families_path %>