config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  resources :genus_notes
  resources :genus
  resources :sub_families
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/genu.rb
class Genu < ApplicationRecord
  belongs_to :sub_family
end

app/controllers/genus_controller.rb
class GenusController < ApplicationController
  before_action :set_genu, only: [:show, :edit, :update, :destroy]


  # GET /genus
  # GET /genus.json
  def index
    @genus = Genu.all
    @sub_family = SubFamily.all
  end

  # GET /genus/1
  # GET /genus/1.json
  def show
  @sub_family = SubFamily.all
  @notes = GenusNote.all
  end

  # GET /genus/new
  def new
    @genu = Genu.new
    @sub_family = SubFamily.all
  end

  # GET /genus/1/edit
  def edit
      @sub_family = SubFamily.all
  end

  # POST /genus
  # POST /genus.json
  def create
    @genu = Genu.new(genu_params)
    @sub_family = SubFamily.all

    respond_to do |format|
      if @genu.save
        format.html { redirect_to @genu, notice: 'Genus Criado.' }
        format.json { render :show, status: :created, location: @genu }
      else
        format.html { render :new }
        format.json { render json: @genu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genus/1
  # PATCH/PUT /genus/1.json
  def update
    @sub_family = SubFamily.all
    respond_to do |format|
      if @genu.update(genu_params)
        format.html { redirect_to @genu, notice: 'Genus Atualizado.' }
        format.json { render :show, status: :ok, location: @genu }
      else
        format.html { render :edit }
        format.json { render json: @genu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genus/1
  # DELETE /genus/1.json
  def destroy
    @sub_family = SubFamily.all
    @genu.destroy
    respond_to do |format|
      format.html { redirect_to genus_url, notice: 'Genus Deletado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genu
      @genu = Genu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genu_params
      params.require(:genu).permit(:name, :sub_family_id, :species_count, :is_published, :first_discovered_at, :fun_fact, :created_at, :updated_at)
    end
end

app/helpers/genus_helper.rb
module GenusHelper
end

app/views/genus/_form.html.erb
<%= form_with(model: genu, local: true) do |form| %>
  <% if genu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genu.errors.count, "error") %> prohibited this genu from being saved:</h2>

      <ul>
        <% genu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <label for="genu_name">Nome</label>
    <%= form.text_field :name, class: 'form-control'%>
  </div>

  <div class="field form-group">
    <label for="genu_sub_family_id">Sub Família</label>
    <select name="genu[sub_family_id]" id="genu_sub_family_id" class="form-control">
        <% sub_family.each do |family| %>
            <option value="<%= family.id %>">
            <%= family.name %>
            </option>
            <% end %>
    </select>
  </div>

  <div class="field form-group">
    <label for="genu_species_count">Número de espécies</label>
    <%= form.number_field :species_count, class: 'form-control' %>
  </div>

  <div style="margin-left: 20px;" class="field form-group">
    <label class="form-check-label">
    <%= form.check_box :is_published, class: 'form-check-input' %>
    Publicar? </label>
  </div>

  <div class="field form-group">
    <label for="genu_first_discovered_at">Descoberto em</label>
    <%= form.date_select :first_discovered_at, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :fun_fact %>
    <%= form.text_area :fun_fact, class: 'form-control' %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
    $('#genu_first_discovered_at_1i').addClass('form-control').addClass('date');
    $('#genu_first_discovered_at_2i').addClass('form-control').addClass('date');
    $('#genu_first_discovered_at_3i').addClass('form-control').addClass('date');
    $('#genu_first_discovered_at_4i').addClass('form-control').addClass('date');
    $('#genu_first_discovered_at_5i').addClass('form-control').addClass('date');
    $('input[name="commit"]').addClass('btn').addClass('btn-success');
</script>

app/views/genus/edit.html.erb
<h1>Editando Genus</h1>

<%= render 'form', genu: @genu, sub_family: @sub_family %>

</br>
<%= link_to raw('<button class="btn btn-primary">Mostrar</button>'), @genu %> |
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), genus_path %>


<script>
$('input[name="commit"]').val("Atualizar Genus");
</script>

app/views/genus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genus</h1>
<%= link_to raw('<button id="new" class="btn btn-dark" style="float: right;margin-top: -45px;">Novo Genus</button>'), new_genu_path %>

<table class="table table-striped display" id="table_id">
  <thead class="table-dark">
    <tr>
      <th>Nome</th>
      <th>Familia Secundária</th>
      <th>Publicado</th>
      <th>Descoberto em</th>
      <th>Fun fact</th>
      <th>Acões</th>
    </tr>
  </thead>

  <tbody>
    <% @genus.each do |genu| %>
    <% family = @sub_family.find(genu.sub_family_id) %>
      <tr>
        <td><%= genu.name %></td>
        <td><%= family.name %></td>
        <td><%= genu.is_published %></td>
        <td><%= genu.first_discovered_at %></td>
        <td><%= genu.fun_fact %></td>
        <td>
        <%= link_to raw('<span style="color:black!important;" class="e fa fa-eye"></span> '), genu %> |
        <%= link_to raw('<span style="color:black!important;" class="e fa fa-pen"></span>'), edit_genu_path(genu) %> |
        <%= link_to raw('<span style="color:black!important;" class="fa fa-trash"></span>'), genu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<script>
    $(document).ready(function () {
        $('#table_id').DataTable({
                    "language": {
                        "info": "Mostrando Página _PAGE_ de _PAGES_",
                        "search": "",
                        "paginate": {
                            "next": "Próxima Página",
                            "previous": "Página Anterior"
                        }
                    },

                });
                $('.dataTables_length').hide();
                $('.dataTables_filter input').addClass('form-control').attr('placeholder','Procurar Genus');
                $('.dataTables_filter').css('float','left');
    });

    $('#new').on('click',function(){
        $('#table_id_filter').remove();
        $('#table_id_info').remove();
        $('#table_id_paginate').remove();
    });

    $('.e').on('click',function(){
            $('#table_id_filter').remove();
            $('#table_id_info').remove();
            $('#table_id_paginate').remove();
        });

        $('.bt').on('click',function(){
                    $('#table_id_filter').remove();
                    $('#table_id_info').remove();
                    $('#table_id_paginate').remove();
                });


</script>

app/views/genus/new.html.erb
<h1>Novo Genus</h1>

<%= render 'form', genu: @genu, sub_family: @sub_family %>

</br>
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), genus_path %>

<script>
$('input[name="commit"]').val("Criar Genus");
</script>

app/views/genus/show.html.erb
<h2 class="genus-name"><%= @genu.name %></h2>
<div class="sea-creature-container">
    <div class="genus-photo"></div>
        <div class="genus-details">
            <div class="genus-details-list">
            <% family = @sub_family.find(@genu.sub_family_id) %>
                <p id="notice"><%= notice %></p>
                <dt>Nome:</dt>
                <dd><%= @genu.name %></dd>

                  <dt><strong>Familia Secundária:</strong></dt>
                  <dd><%= family.name %></dd>

                  <dt><strong>Descoberto em:</strong></dt>
                  <dd><%= @genu.first_discovered_at %></dd>

                  <dt><strong>Fun fact:</strong></dt>
                  <dd><%= @genu.fun_fact %></dd>

                <%= link_to raw('<button class="btn btn-primary">Editar</button>'), edit_genu_path(@genu) %> |
                <%= link_to raw('<button class="btn btn-dark">Voltar</button>'), genus_path %>
            </div>
        </div>
</div>

<div class="notes-container">
    <h2 class="notes-header">Notas</h2>
    <a href="/genus_notes/new"><i style="margin-top: 7px;" id="a-plus" class="fa fa-plus plus-btn">&nbsp;</i></div></a>
</div>


<section id="cd-timeline">
<% @notes.each do |note| %>
    <div class="cd-timeline-block">
        <div class="cd-timeline-img">
            <%= image_tag (note.user_avatar_filename), class: "img-circle", style: "border-radius: 50%;"%>
        </div>

    <div class="cd-timeline-content">
        <h2><a href="#">Nota</a></h2>
        <p><%= note.note %></p>
        <span class="cd-date"</span>
    </div>
    </div>
    <% end %>
</section>