config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home/index'
  resources :genus_notes
  resources :genus
  resources :sub_families
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/genus_note.rb
class GenusNote < ApplicationRecord
  belongs_to :genus
end

app/controllers/genus_notes_controller.rb
class GenusNotesController < ApplicationController
  before_action :set_genus_note, only: [:show, :edit, :update, :destroy]

  # GET /genus_notes
  # GET /genus_notes.json
  def index
    @genus = Genu.all
    @genus_notes = GenusNote.all
  end

  # GET /genus_notes/1
  # GET /genus_notes/1.json
  def show
  @genus = Genu.all
  end

  # GET /genus_notes/new
  def new
    @genus = Genu.all
    @genus_note = GenusNote.new
  end

  # GET /genus_notes/1/edit
  def edit
  @genus = Genu.all
  end

  # POST /genus_notes
  # POST /genus_notes.json
  def create
    @genus = Genu.all
    @genus_note = GenusNote.new(genus_note_params)

    respond_to do |format|
      if @genus_note.save
        format.html { redirect_to @genus_note, notice: 'Nota Criada.' }
        format.json { render :show, status: :created, location: @genus_note }
      else
        format.html { render :new }
        format.json { render json: @genus_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genus_notes/1
  # PATCH/PUT /genus_notes/1.json
  def update
    @genus = Genu.all
    respond_to do |format|
      if @genus_note.update(genus_note_params)
        format.html { redirect_to @genus_note, notice: 'Nota Atualizada' }
        format.json { render :show, status: :ok, location: @genus_note }
      else
        format.html { render :edit }
        format.json { render json: @genus_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genus_notes/1
  # DELETE /genus_notes/1.json
  def destroy
    @genus = Genu.all
    @genus_note.destroy
    respond_to do |format|
      format.html { redirect_to genus_notes_url, notice: 'Nota Deletada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genus_note
      @genus_note = GenusNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genus_note_params
      params.require(:genus_note).permit(:genus_id, :user_avatar_filename, :note, :created_at, :updated_at)
    end
end

app/helpers/genus_notes_helper.rb
module GenusNotesHelper
end

app/views/genus_notes/_form.html.erb
<%= form_with(model: genus_note, local: true) do |form| %>
  <% if genus_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genus_note.errors.count, "error") %> prohibited this genus_note from being saved:</h2>

      <ul>
        <% genus_note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :genus_id %>
    <select class="form-control" name="genus_note[genus_id]" id="genus_note_genus_id">
        <% genus.each do |genu| %>
            <option value="<%= genu.id %>">
            <%= genu.name %>
            </option>
        <% end %>
    </select>
  </div>

  <div class="field form-group">
    <%= form.label :user_avatar_filename %>
    <select class="form-control" name="genus_note[user_avatar_filename]" id="genus_note_user_avatar_filename">
        <option value="ryan.jpeg">Ryan</option>
        <option value="leanna.jpeg">Leanna</option>
    </select>
   </div>

  <div class="field form-group">
    <%= form.label :note %>
    <%= form.text_area :note, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
$('input[name="commit"]').addClass('btn').addClass('btn-success');
</script>

app/views/genus_notes/edit.html.erb
<h1>Editando Nota</h1>

<%= render 'form', genus_note: @genus_note, genus: @genus %>

</br>
<%= link_to raw('<button class="btn btn-primary">Mostrar</button>'), @genus_note %> |
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), genus_notes_path %>


<script>
$('input[name="commit"]').val("Atualizar Nota");
</script>

app/views/genus_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genus Notes</h1>
<%= link_to raw('<button id="new" class="btn btn-dark" style="float: right;margin-top: -45px;">Novo Genus</button>'), new_genus_note_path %>
<table class="table table-striped display" id="table2_id">
  <thead class="table-dark">
    <tr>
      <th>Genus</th>
      <th>Avatar</th>
      <th>Note</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @genus_notes.each do |genus_note| %>
    <% @genu = @genus.find(genus_note.genus_id) %>
      <tr>
        <td><%= @genu.name %></td>
        <td><%= image_tag (genus_note.user_avatar_filename), class: "logo-icon", style: "border-radius: 50%;height: 35px;margin-left: 20px;" %></td>
        <td><%= genus_note.note %></td>
        <td><%= link_to raw('<span style="color:black!important;" class="e fa fa-eye"></span> '), genus_note %> |
        <%= link_to raw('<span style="color:black!important;" class="e fa fa-pen"></span>'), edit_genus_note_path(genus_note) %> |
        <%= link_to raw('<span style="color:black!important;" class="fa fa-trash"></span>'), genus_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<br>
<script>
    $(document).ready(function () {
        $('#table2_id').DataTable({
                    "language": {
                        "info": "Mostrando Página _PAGE_ de _PAGES_",
                        "search": "",
                        "paginate": {
                            "next": "Próxima Página",
                            "previous": "Página Anterior"
                        }
                    },

                });
                $('.dataTables_length').hide();
                $('.dataTables_filter input').addClass('form-control').attr('placeholder','Procurar Nota');
                $('.dataTables_filter').css('float','left');
    });

    $('#new2').on('click',function(){
        $('#table2_id_filter').remove();
        $('#table2_id_info').remove();
        $('#table2_id_paginate').remove();
    });

    $('.e2').on('click',function(){
            $('#table2_id_filter').remove();
            $('#table2_id_info').remove();
            $('#table2_id_paginate').remove();
        });

        $('.bt').on('click',function(){
                    $('#table2_id_filter').remove();
                    $('#table2_id_info').remove();
                    $('#table2_id_paginate').remove();
                });

</script>

app/views/genus_notes/new.html.erb
<h1>Nova Nota</h1>

<%= render 'form', genus_note: @genus_note, genus: @genus %>

</br>
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), genus_notes_path %>


<script>
$('input[name="commit"]').val("Criar Nota");
</script>

app/views/genus_notes/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
<tbody>
<tr>
  <th><strong>Genus:</strong></th>
  <td><% @genu = @genus.find(@genus_note.genus_id) %>
  <%= @genu.name %></td>
</tr>

<tr>
  <th><strong>User avatar filename:</strong></th>
  <td><%= @genus_note.user_avatar_filename %></td>
</tr>

<tr>
  <th><strong>Note:</strong></th>
  <td><%= @genus_note.note %></td>
</tr>

<tr>
  <th><strong>Created at:</strong></th>
  <td><%= @genus_note.created_at %></td>
</tr>

<tr>
  <th><strong>Updated at:</strong></th>
  <td><%= @genus_note.updated_at %></td>
</tr>
</tbody>
</table>
<%= link_to raw('<button class="btn btn-primary">Editar</button>'), edit_genus_note_path(@genus_note) %> |
<%= link_to raw('<button class="btn btn-dark">Voltar</button>'), genus_notes_path %>